### PR TITLE
Feature/feature branch2

### PR DESCRIPTION
**Pull request by realisticattorney**
Milestones for this project were:

-Lunch a website with a join table relation between users & events
-Render events classified as upcoming and past events

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @realisticattorney :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] The event's show page should display the list of attendants  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] The user's show page should display events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] An event creator is the only one who should be able to edit an event. Kindly remove the `Edit` button for other users on the events show page.

#### Models

##### Event

* [ ] it has creation date as attribute ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/event_date_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] scope for upcoming events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/scopes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

```ruby
scope :upcoming, -> { where('date >= ?', Time.zone.now) }
```

* [ ] scope for previous events ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/scopes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

```ruby
scope :previous, -> { where('date < ?',  Time.zone.now) }
```

#### Controllers

##### EventsController

###### `create` action

* [ ] uses #build method on association, i.e. `current_user.events.build(event_params)` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/build_method_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

###### `index` action

* [ ] lists past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

##### UsersController

###### `show` action

* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

### Make the requested changes and request for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @realisticattorney, 👋🏽 
 **Thank you for the good job you got going on and for implementing the requested changes. The BaseApp looks good.**

## REQUIRED CHANGES

- [ ] When I create a new event, the process is not successful. Kindly help your users create a new event successfully. `Please review the problems below:`
Screenshot_2021-02-22_06-04-16

- [ ] authentication should have integration tests (Rspec + Capybara) [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/)
- [ ] event managment features should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by blackpintz — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights

- **Professional README file.**
- **The app runs on the browser.**

### Mandatory Requirements

1). **Add `.DS_Store` file in `.gitignore`  and remove it from your git tree.**

2). **An event show page should display a list of its attendants.**

3). **A user's show page should also list the events the user has created.**

4). **Some` rspec` tests are failing. See screenshot below.**

rspec


### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Hello Team :wave:
Status: Changes Required :recycle:

Great job :clap:
Thanks for adding password in the authentication page. Even if It is not required, you have added it. I can see that you have put a lot of effort on this project. In addition to that, your App works but before approving this project let's cover a few details together to make your project better :blush: :arrow_double_down: . I am sure that it will not take a lot of time:

REQUIRED:
- [ ] In your readme file:
1.  **Setup instructions:** Before **$ rails db:migrate** you should ask user to create databases through **$ rails db:create** then, in order to run the app, user must use the command **$ rails s**.
2. Add instructions for unit tests.

- [ ] Delete all comments
- [ ] Create separate folders for each kind of tests (Models/Features)

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @realisticattorney  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The screenshot in readme file is broken, please fix it
- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from Pathwright) 
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by realisticattorney** [comment]
HI @descholar-ceo. .DS_Store file was already added to gitignore when you did the review. What else can I do about it? Thanks for your time

**Comment by descholar-ceo** [comment]
> HI @descholar-ceo. .DS_Store file was already added to gitignore when you did the review. What else can I do about it? Thanks for your time

Hello @realisticattorney, thank you for reaching out for more clarification. Actually you should remove the `.DS_Store` from the root directory of your project. Then since it's alredy on `.gitignore` file, it won't be committed anymore

**Comment by realisticattorney** [comment]
@descholar-ceo  thanks you your quick answer. Unfortunately, I can't find the .DS_Store file . I've looked for it through the github search bar and in the folder but it's showing no results. Could you tell me where it is?

**Comment by descholar-ceo** [comment]
> @descholar-ceo thanks you your quick answer. Unfortunately, I can't find the .DS_Store file . I've looked for it through the github search bar and in the folder but it's showing no results. Could you tell me where it is?
> 
> EDIT: Just found it. Thank you

That's nice @realisticattorney , keep up the good job and good luck with your project!

**Review by whiz25 — APPROVED** [review]
## Approved ✅ 
Nice work @realisticattorney . You made the requested changes. Please merge and proceed to then next project.


### Martin Afani

**Pull request merged**
